package crms;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import static sun.security.jgss.GSSUtil.login;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Da Silva
 */
public class criminalManagement1 extends JFrame {

    /**
     * Creates new form criminalManagement
     */
     Connection conn;
  
    PreparedStatement pst;
  
    ResultSet rs;
  
  public String gender;
  
  String ImgPath = null;
  
  int xx;
  
  int xy;
  
  String path;
  
  byte[] photo = null;
  
  int pos = 0;
    
    public criminalManagement1() {
        initComponents();
        firstCall();
        this.setLocationRelativeTo(null);
    }
    
    private void firstCall() {
    setLocationRelativeTo(null);
    setResizable(false);
    getConnection();
    displayToTable();
    setIcon();
    this.txt_stat.setLineWrap(true);
    this.txt_stat.setWrapStyleWord(true);
    this.querytxt.setLineWrap(true);
    this.querytxt.setWrapStyleWord(true);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        records = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        off_table = new javax.swing.JTable();
        txt_lname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_mname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_add = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jgender = new javax.swing.JComboBox<>();
        jdob = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        txt_lga = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_stat = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jsoo = new javax.swing.JComboBox<>();
        add_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        del_btn = new javax.swing.JButton();
        prev_btn = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txt_crime = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        next_btn1 = new javax.swing.JButton();
        query = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        qprint = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        querytxt = new javax.swing.JTextArea();
        database = new javax.swing.JPanel();
        backup_btn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        off_tab = new javax.swing.JTable();
        changepassword = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nig police.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home_48px.png"))); // NOI18N
        jLabel1.setLabelFor(dashboard);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setLabelFor(dashboard);
        jLabel3.setText("Dashboard");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Create Document_48px.png"))); // NOI18N
        jLabel4.setLabelFor(records);
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setLabelFor(records);
        jLabel5.setText("Record");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Query");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search_48px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setLabelFor(database);
        jLabel8.setText("Database");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Data Backup_48px.png"))); // NOI18N
        jLabel9.setLabelFor(database);
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sign Out_48px.png"))); // NOI18N
        jLabel27.setLabelFor(database);
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setLabelFor(database);
        jLabel31.setText("Logout");
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel31MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel31)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sign Out_25px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel11.setText("Criminal Record and Management System");

        jPanel3.setToolTipText("record");
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Create Document_96px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Record");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(88, 88, 88))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel13)
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel4.setToolTipText("record");
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search_96px.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Query");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(9, 9, 9)))
                .addGap(88, 88, 88))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel6.setToolTipText("record");
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.setPreferredSize(new java.awt.Dimension(279, 281));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Data Backup_96px.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("DataBase");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(78, 78, 78))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel16)
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel10)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11)))
                .addGap(145, 145, 145)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jPanel5.add(dashboard, "card3");

        records.setBackground(new java.awt.Color(255, 255, 255));
        records.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Last Name:");
        records.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 35, -1, -1));

        off_table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        off_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Criminal Id", "lname", "fname", "mname", "img", "dob", "gender", "address", "soor", "lga", "stat", "crime"
            }
        ));
        off_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                off_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(off_table);

        records.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 542, 1130, 150));

        txt_lname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        records.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 32, 214, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("First Name:");
        records.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, -1, -1));

        txt_fname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });
        records.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 95, 214, -1));

        txt_mname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        records.add(txt_mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 158, 214, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Middle Name:");
        records.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 161, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Date of Birth:");
        records.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 224, -1, -1));

        txt_add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        records.add(txt_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 359, 214, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Gender:");
        records.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 288, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Address:");
        records.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 362, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("State of Origin:");
        records.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 432, -1, -1));

        jgender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Male", "Female" }));
        jgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgenderActionPerformed(evt);
            }
        });
        records.add(jgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 280, 214, 40));

        jdob.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        records.add(jdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 214, 38));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("LGA:");
        records.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 499, -1, -1));

        txt_lga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        records.add(txt_lga, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 499, 214, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Image:");
        records.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, -1));

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pic.png"))); // NOI18N
        records.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Statement:");
        records.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        txt_stat.setColumns(20);
        txt_stat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_stat.setRows(5);
        jScrollPane2.setViewportView(txt_stat);

        records.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 290, 160));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        records.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, -1, -1));

        clear_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clear_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear_25px.png"))); // NOI18N
        clear_btn.setText("Clear");
        clear_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clear_btnMousePressed(evt);
            }
        });
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        records.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 430, 130, -1));

        jsoo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jsoo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "FC|Abuja", "AB|Abia", "AD|Adamawa", "AK|Akwa Ibom", "AN|Anambra", "BA|Bauchi", "BY|Bayelsa", "BE|Benue", "BO|Borno", "CR|Cross River", "DE|Delta", "EB|Ebonyi", "ED|Edo", "EK|Ekiti", "EN|Enugu", "GO|Gombe", "IM|Imo", "JI|Jigawa", "KD|Kaduna", "KN|Kano", "KT|Katsina", "KE|Kebbi", "KO|Kogi", "KW|Kwara", "LA|Lagos", "NA|Nassarawa", "NI|Niger", "OG|Ogun", "ON|Ondo", "OS|Osun", "OY|Oyo", "PL|Plateau", "RI|Rivers", "SO|Sokoto", "TA|Taraba", "YO|Yobe", "ZA|Zamfara" }));
        records.add(jsoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 220, 40));

        add_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add File_25px.png"))); // NOI18N
        add_btn.setText("Add ");
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_btnMousePressed(evt);
            }
        });
        records.add(add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 140, -1));

        update_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Update_25px.png"))); // NOI18N
        update_btn.setText("Update");
        update_btn.setPreferredSize(new java.awt.Dimension(101, 33));
        update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                update_btnMousePressed(evt);
            }
        });
        records.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 130, -1));

        del_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        del_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete Row_25px.png"))); // NOI18N
        del_btn.setText("Delete");
        del_btn.setPreferredSize(new java.awt.Dimension(101, 33));
        del_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                del_btnMousePressed(evt);
            }
        });
        records.add(del_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 130, -1));

        prev_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prev_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back_25px.png"))); // NOI18N
        prev_btn.setText("Prev");
        prev_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_btnActionPerformed(evt);
            }
        });
        records.add(prev_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 130, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Crime:");
        records.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        txt_crime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        records.add(txt_crime, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 280, 40));

        txt_id.setEditable(false);
        records.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 40, -1));

        next_btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        next_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Forward_25px.png"))); // NOI18N
        next_btn1.setText("Next");
        next_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btn1ActionPerformed(evt);
            }
        });
        records.add(next_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 130, -1));

        jPanel5.add(records, "card2");

        query.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("Criminal Last Name:");

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/query_30px.png"))); // NOI18N
        jButton7.setText("Search");

        qprint.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print_30px.png"))); // NOI18N
        qprint.setText("Print");
        qprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qprintMouseClicked(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear_25px.png"))); // NOI18N
        jButton9.setText("Clear");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton9MousePressed(evt);
            }
        });

        querytxt.setColumns(20);
        querytxt.setRows(5);
        jScrollPane3.setViewportView(querytxt);

        javax.swing.GroupLayout queryLayout = new javax.swing.GroupLayout(query);
        query.setLayout(queryLayout);
        queryLayout.setHorizontalGroup(
            queryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(queryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(queryLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(35, 35, 35)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(qprint, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        queryLayout.setVerticalGroup(
            queryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(queryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(qprint)
                    .addComponent(jButton9))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5.add(query, "card6");

        database.setBackground(new java.awt.Color(255, 255, 255));

        backup_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backup_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear_25px.png"))); // NOI18N
        backup_btn.setText("BackUp");
        backup_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backup_btnMousePressed(evt);
            }
        });
        backup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backup_btnActionPerformed(evt);
            }
        });

        off_tab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        off_tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Criminal Id", "lname", "fname", "mname", "img", "dob", "gender", "address", "soor", "lga", "stat", "crime"
            }
        ));
        off_tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                off_tabMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(off_tab);

        javax.swing.GroupLayout databaseLayout = new javax.swing.GroupLayout(database);
        database.setLayout(databaseLayout);
        databaseLayout.setHorizontalGroup(
            databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backup_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        databaseLayout.setVerticalGroup(
            databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, databaseLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(backup_btn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel5.add(database, "card4");

        changepassword.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout changepasswordLayout = new javax.swing.GroupLayout(changepassword);
        changepassword.setLayout(changepasswordLayout);
        changepasswordLayout.setHorizontalGroup(
            changepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1154, Short.MAX_VALUE)
        );
        changepasswordLayout.setVerticalGroup(
            changepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        jPanel5.add(changepassword, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Add Record");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Edit Record");
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Database");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Record");

        jMenuItem3.setText("All Record");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        this.jPanel5.removeAll();
        jPanel5.add(dashboard);
        this.jPanel5.validate();
        this.jPanel5.repaint();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        this.jPanel5.removeAll();
        jPanel5.add(records);
        this.jPanel5.validate();
        this.jPanel5.repaint();
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        this.jPanel5.removeAll();
        jPanel5.add(query);
        this.jPanel5.validate();
        this.jPanel5.repaint();
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        this.jPanel5.removeAll();
        jPanel5.add(database);
        this.jPanel5.validate();
        this.jPanel5.repaint();
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
       int a = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "NPF CRIMINAL RECORD AND MANAGEMENT SYSTEM", 0);
      if (a == 0)
      try {
        login lg = new login();
        dispose();
        lg.setVisible(true);
      } catch (Exception ex) {
        Logger.getLogger(criminalManagement1.class.getName()).log(Level.SEVERE, (String)null, ex);
      }  
    }//GEN-LAST:event_jLabel10MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        this.jPanel5.removeAll();
        jPanel5.add(records);
        this.jPanel5.validate();
        this.jPanel5.repaint();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
           this.jPanel5.removeAll();
        jPanel5.add(query);
        this.jPanel5.validate();
        this.jPanel5.repaint();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
         this.jPanel5.removeAll();
        jPanel5.add(database);
        this.jPanel5.validate();
        this.jPanel5.repaint();
    }//GEN-LAST:event_jPanel6MousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jgenderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JFileChooser file = new JFileChooser();
    file.setCurrentDirectory(new File(System.getProperty("user.home")));
    FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", new String[] { "jpg", "png" });
    file.addChoosableFileFilter(filter);
    int result = file.showOpenDialog(null);
    if (result == 0) {
      this.lbl_image.setIcon((Icon)null);
      File selectedFile = file.getSelectedFile();
      this.path = selectedFile.getAbsolutePath();
      this.lbl_image.setIcon(ResizeImage(this.path, (byte[])null));
      this.ImgPath = this.path;
      try {
        File image = new File(this.path);
        FileInputStream fis = new FileInputStream(image);
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        byte[] buf = new byte[1024];
        int readNum;
        while ((readNum = fis.read(buf)) != -1)
          bos.write(buf, 0, readNum); 
        this.photo = bos.toByteArray();
      } catch (IOException e) {
        JOptionPane.showMessageDialog(null, e);
      } 
    } else {
      System.out.println("No File Selected");
    } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void off_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_off_tableMouseClicked
        // TODO add your handling code here:
        int index = this.off_table.getSelectedRow();
        showItem(index);
    }//GEN-LAST:event_off_tableMouseClicked

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_clear_btnActionPerformed

    private void prev_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_btnActionPerformed
        // TODO add your handling code here:
        this.pos--;
        if (this.pos < 0)
        this.pos = 0; 
        showItem(this.pos);
    }//GEN-LAST:event_prev_btnActionPerformed

    private void add_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMousePressed
        // TODO add your handling code here:
        try {
      addBtn();
    } catch (FileNotFoundException ex) {
      System.out.println("Error in  adding");
    } catch (SQLException ex) {
      Logger.getLogger(criminalManagement1.class.getName()).log(Level.SEVERE, (String)null, ex);
    } 
    }//GEN-LAST:event_add_btnMousePressed

    private void update_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_btnMousePressed
        // TODO add your handling code here:
        try {
      updateBtn();
    } catch (SQLException ex) {
      Logger.getLogger(criminalManagement1.class.getName()).log(Level.SEVERE, (String)null, ex);
    }    catch (FileNotFoundException ex) { 
             Logger.getLogger(criminalManagement1.class.getName()).log(Level.SEVERE, null, ex);
         } 
    }//GEN-LAST:event_update_btnMousePressed

    private void del_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del_btnMousePressed
        // TODO add your handling code here:
        if (!this.txt_id.getText().equals("")) {
      int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?", "Delete", 0);
      if (p == 0)
        try {
          String sql = "DELETE FROM `criminal table` WHERE `criminal_table`.`criminal_id` =?";
          this.pst = this.conn.prepareStatement(sql);
          this.pst.setString(1, this.txt_id.getText());
          this.pst.execute();
          clear();
         // DefaultTableModel model = (DefaultTableModel)this.off_tb.getModel();
          DefaultTableModel model1 = (DefaultTableModel)this.off_table.getModel();
          model1.setRowCount(0);
        //  model.setRowCount(0);
          displayToTable();
          JOptionPane.showMessageDialog(this, "Record Deleted");
        } catch (SQLException f) {
          System.out.println(f);
        }  
    } else {
      JOptionPane.showMessageDialog(null, "Record Not Deleted : No Id To Delete");
    } 
    }//GEN-LAST:event_del_btnMousePressed

    private void next_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_next_btn1ActionPerformed

    private void clear_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_btnMousePressed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clear_btnMousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - this.xx, y - this.xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void qprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qprintMouseClicked
        // TODO add your handling code here:
        //this.qprint.print();
    }//GEN-LAST:event_qprintMouseClicked

    private void jButton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MousePressed
        // TODO add your handling code here:
        this.querytxt.setText("");
    }//GEN-LAST:event_jButton9MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        // TODO add your handling code here:
        setOpacity(1.0F);
    }//GEN-LAST:event_jPanel2MouseReleased

    private void backup_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backup_btnMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_backup_btnMousePressed

    private void backup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backup_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backup_btnActionPerformed

    private void off_tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_off_tabMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_off_tabMouseClicked

    private void jLabel31MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MousePressed
        // TODO add your handling code here:
           int a = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "NPF CRIMINAL RECORD AND MANAGEMENT SYSTEM", 0);
      if (a == 0)
      try {
        login lg = new login();
        dispose();
        lg.setVisible(true);
      } catch (Exception ex) {
        Logger.getLogger(criminalManagement1.class.getName()).log(Level.SEVERE, (String)null, ex);
      }  
    }//GEN-LAST:event_jLabel31MousePressed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          try {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      } catch (ClassNotFoundException|javax.swing.UnsupportedLookAndFeelException ex) {
        Logger.getLogger(login.class.getName()).log(Level.SEVERE, (String)null, ex);
      } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(criminalManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new criminalManagement1().setVisible(true);
          });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton backup_btn;
    private javax.swing.JPanel changepassword;
    private javax.swing.JButton clear_btn;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel database;
    private javax.swing.JButton del_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField7;
    private com.toedter.calendar.JDateChooser jdob;
    private javax.swing.JComboBox<String> jgender;
    private javax.swing.JComboBox<String> jsoo;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JButton next_btn1;
    private javax.swing.JTable off_tab;
    private javax.swing.JTable off_table;
    private javax.swing.JButton prev_btn;
    private javax.swing.JButton qprint;
    private javax.swing.JPanel query;
    private javax.swing.JTextArea querytxt;
    private javax.swing.JPanel records;
    private javax.swing.JTextField txt_add;
    private javax.swing.JTextField txt_crime;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lga;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mname;
    private javax.swing.JTextArea txt_stat;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables


 private void setIcon() {
   // setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/Nig police.png")));
  }
  
  private Connection getConnection() {
    try {
      Class.forName("com.mysql.jdbc.Driver");
      String db_url = "jdbc:mysql://localhost:3307/sms";
        try {
            this.conn = DriverManager.getConnection(db_url, "root", "centre4UNG.");
        } catch (SQLException ex) {
            Logger.getLogger(criminalManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }
    } catch (ClassNotFoundException ex) {
      JOptionPane.showMessageDialog(null, "No Connection To Database Made.");
      System.exit(0);
    } 
    return this.conn;
  }
  
  private void clear() {
    this.txt_lname.setText("");
    this.txt_fname.setText("");
    this.txt_mname.setText("");
    this.jdob.setCalendar(null);
    this.jgender.setSelectedIndex(0);
    this.txt_add.setText("");
    this.jsoo.setSelectedIndex(0);
    this.txt_lga.setText("");
    this.txt_stat.setText("");
    this.txt_crime.setText("");
    lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pic.png")));
  }
  
  public final void displayToTable() {
    DefaultTableModel model = (DefaultTableModel)this.off_table.getModel();
     DefaultTableModel model1 = (DefaultTableModel)this.off_tab.getModel();
    try (
            Statement stmt = this.conn.createStatement()) {
      String qurry = "Select * from `criminal_table`";
      this.rs = stmt.executeQuery(qurry);
      while (this.rs.next()) {
        String d = this.rs.getString("criminal_id");
        String d1 = this.rs.getString("last_name");
        String d2 = this.rs.getString("first_name");
        String d3 = this.rs.getString("middle_name");
        byte[] img = this.rs.getBytes("image");
        String d4 = this.rs.getString("dob");
        String d5 = this.rs.getString("gender");
        String d6 = this.rs.getString("address");
        String d7 = this.rs.getString("soor");
        String d8 = this.rs.getString("lga");
        String d9 = this.rs.getString("statement");
        String d10 = this.rs.getString("crime");
        
        model.addRow(new Object[] { 
              d, d1, d2, d3, img, d4, d5, d6, d7, d8, d9, 
              d10 });
        
        model1.addRow(new Object[] { 
              d, d1, d2, d3, img, d4, d5, d6, d7, d8, d9, 
              d10 });
      } 
    } catch (SQLException e) {
      JOptionPane.showMessageDialog(null, e);
    } 
  }
  

  
  private ArrayList<user> getUsersList() {
    ArrayList<user> userList = new ArrayList<>();
    String sss = "SELECT * FROM `criminal_table`";
    try {
      Statement st = this.conn.createStatement();
      this.rs = st.executeQuery(sss);
      while (this.rs.next()) {
        user usr;
           usr = new user(this.rs.getString("criminal_id"), this.rs.getString("last_name"), this.rs.getString("first_name"), this.rs.getString("middle_name"), this.rs.getBytes("image"), this.rs.getString("dob"), this.rs.getString("gender"), this.rs.getString("address"), this.rs.getString("soor"), this.rs.getString("lga"), this.rs.getString("statement"), this.rs.getString("crime"));
        userList.add(usr);
      } 
    } catch (SQLException sQLException) {}
    return userList;
  }
  
  public void executeSQLQuery(String query, String message) {
    try {
      Statement st = this.conn.createStatement();
      if (st.executeUpdate(query) == 1) {
        DefaultTableModel model = (DefaultTableModel)this.off_table.getModel();
        DefaultTableModel model1 = (DefaultTableModel)this.off_table.getModel();
        model.setRowCount(0);
        model1.setRowCount(0);
        displayToTable();
        JOptionPane.showMessageDialog(this, "Data " + message + " Successful");
      } else {
        JOptionPane.showMessageDialog(this, "Data Not " + message);
      } 
    } catch (HeadlessException e) {
      System.out.println(e);
    }    catch (SQLException ex) { 
             Logger.getLogger(criminalManagement1.class.getName()).log(Level.SEVERE, null, ex);
         } 
  }
  
  public ImageIcon ResizeImage(String imagePath, byte[] pic) {
    ImageIcon myImage = null;
    if (imagePath != null) {
      myImage = new ImageIcon(imagePath);
    } else {
      myImage = new ImageIcon(pic);
    } 
    Image img = myImage.getImage();
    Image img2 = img.getScaledInstance(this.lbl_image.getWidth(), this.lbl_image.getHeight(), 4);
    ImageIcon image = new ImageIcon(img2);
    return image;
  }
  
  public boolean checkInput() {
    if (this.txt_lname
      .getText() == null || this.txt_fname
      .getText() == null || this.txt_mname
      .getText() == null || this.jdob
      .getDate() == null || this.jgender
      .getSelectedItem().equals("Select...")|| this.txt_add
      .getText() == null || this.jsoo
      .getSelectedItem().equals("Select...") || this.txt_lga
      .getText() == null || this.txt_stat
      .getText() == null ||  this.txt_crime
      .getText() == null   
            )
      return false; 
    return true;
  }
  
  public void addBtn() throws FileNotFoundException, FileNotFoundException, SQLException {
    if (checkInput() && this.ImgPath != null) {
      int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?", "Add Record", 0);
      if (p == 0)
        try {
          this.conn = getConnection();
            System.out.println("1");
          String aa = "INSERT INTO `criminal_table` (`last_name`, `first_name`, `middle_name`, `image`, `dob`, `gender`, `address`, `soor`, `lga`, `statement`, `crime`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
          System.out.println("2");
          this.pst = this.conn.prepareStatement(aa);
           System.out.println("3");
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //  this.pst.setString(1, this.txt_id.getText());
          this.pst.setString(1, this.txt_lname.getText());
          this.pst.setString(2, this.txt_fname.getText());
          this.pst.setString(3, this.txt_mname.getText());
          InputStream img = new FileInputStream(new File(this.ImgPath));
          this.pst.setBlob(4, img);
          String addDob = sdf.format(this.jdob.getDate());
          this.pst.setString(5, addDob);
          this.pst.setString(6, this.jgender.getSelectedItem().toString());
          this.pst.setString(7, this.txt_add.getText());
          this.pst.setString(8, this.jsoo.getSelectedItem().toString());
          this.pst.setString(9, this.txt_lga.getText());
          this.pst.setString(10, this.txt_stat.getText());
          this.pst.setString(11, this.txt_crime.getText());
           System.out.println("4");
          this.pst.execute();
           System.out.println("5");
          JOptionPane.showMessageDialog(this, "Data Inserted  Successfully");
          DefaultTableModel model = (DefaultTableModel)this.off_tab .getModel();
           DefaultTableModel model1 = (DefaultTableModel)this.off_table.getModel();
           model1.setRowCount(0);
          model.setRowCount(0);
          displayToTable();
        } catch (FileNotFoundException|NumberFormatException|SQLException e) {
          System.out.println(e);
        } finally {
          this.pst.close();
          this.conn.close();
        }  
    } else {
      JOptionPane.showMessageDialog(this, "One Or More Field Are Empty ");
    } 
  }
  
  public void updateBtn() throws SQLException, FileNotFoundException {
    if (checkInput() && this.txt_id.getText() != null)
      if (this.ImgPath == null) {
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to Update record?", "Update Record", 0);
        if (p == 0)
          try {
            this.conn = getConnection();
            String query = "UPDATE `criminal_table` SET `last_name` = ?, `first_name` = ? , `middle_name` = ? ,`image` = ?, `dob` = ? , `gender` = ? , `address` = ? , `soor` = ?, `lga` = ?, `statement` = ?, `crime` = ? WHERE `id` =?";
            this.pst = this.conn.prepareStatement(query);
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          
          this.pst.setString(1, this.txt_lname.getText());
          this.pst.setString(2, this.txt_fname.getText());
          this.pst.setString(3, this.txt_mname.getText());
          InputStream img = new FileInputStream(new File(this.ImgPath));
          this.pst.setBlob(4, img);
          String addDob = sdf.format(this.jdob.getDate());
          this.pst.setString(5, addDob);
          this.pst.setString(6, this.jgender.getSelectedItem().toString());
          this.pst.setString(7, this.txt_add.getText());
          this.pst.setString(8, this.jsoo.getSelectedItem().toString());
          this.pst.setString(9, this.txt_lga.getText());
          this.pst.setString(10, this.txt_stat.getText());
          this.pst.setString(11, this.txt_crime.getText());
          
          this.pst.setString(12, this.txt_id.getText());
          
            this.pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Update Successful");
            DefaultTableModel model = (DefaultTableModel)this.off_table.getModel();
            DefaultTableModel model1 = (DefaultTableModel)this.off_table.getModel();
            model1.setRowCount(0);
            model.setRowCount(0);
            displayToTable();
          } catch (NumberFormatException|SQLException e) {
            System.out.println(e);
          }  
      } else {
        try {
          this.conn = getConnection();
          String query = "UPDATE `criminal_table` SET `last_name` = ?, `first_name` = ?, `middle_name` = ?, `dob` = ?, `gender` = ?, `address` = ?, `soor` = ?, `lga` = ?, `statement` = ?, `crime` = ? WHERE `criminal_table`.`criminal_id` = ?";
          this.pst = this.conn.prepareStatement(query);
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          this.pst.setString(1, this.txt_lname.getText());
          this.pst.setString(2, this.txt_fname.getText());
          this.pst.setString(3, this.txt_mname.getText());
          InputStream img = new FileInputStream(new File(this.ImgPath));
          this.pst.setBlob(4, img);
          String addDob = sdf.format(this.jdob.getDate());
          this.pst.setString(5, addDob);
          this.pst.setString(6, this.jgender.getSelectedItem().toString());
          this.pst.setString(7, this.txt_add.getText());
          this.pst.setString(8, this.jsoo.getSelectedItem().toString());
          this.pst.setString(9, this.txt_lga.getText());
          this.pst.setString(10,this.txt_stat.getText());
          this.pst.setString(11, this.txt_crime.getText());
          
          this.pst.setString(12, this.txt_id.getText());
          
            System.out.println("Reached");
          this.pst.executeUpdate();
          JOptionPane.showMessageDialog(this, "Update Successful");
          DefaultTableModel model = (DefaultTableModel)this.off_table.getModel();
          DefaultTableModel model1 = (DefaultTableModel)this.off_table.getModel();
          model1.setRowCount(0);
          model.setRowCount(0);
          displayToTable();
        } catch (SQLException|FileNotFoundException ex) {
          Logger.getLogger(criminalManagement1.class.getName()).log(Level.SEVERE, (String)null, ex);
        } finally {
          this.pst.close();
          this.conn.close();
        } 
      }  
  }
  
   public void showItem(int index) {
    TableModel model = this.off_table.getModel();
    this.txt_id.setText(((user)getUsersList().get(index)).getcriminal_id());
    this.txt_lname.setText(((user)getUsersList().get(index)).getlast_name());
    this.txt_fname.setText(((user)getUsersList().get(index)).getfirst_name());
    this.txt_mname.setText(((user)getUsersList().get(index)).getmiddle_name());
    this.lbl_image.setIcon(ResizeImage((String)null, ((user)getUsersList().get(index)).getimage()));
    
    try {
      Date addDate = (new SimpleDateFormat("yyyy-MM-dd")).parse(((user)getUsersList().get(index)).getdob());
      this.jdob.setDate(addDate);
    } catch (ParseException parseException) {}
    
    this.jgender.setSelectedItem(((user)getUsersList().get(index)).getgender());
    this.txt_add.setText(((user)getUsersList().get(index)).getaddress());
    this.jsoo.setSelectedItem(((user)getUsersList().get(index)).getsoor());
    this.txt_lga.setText(((user)getUsersList().get(index)).getlga());
    this.txt_stat.setText(((user)getUsersList().get(index)).getstatement());
    this.txt_crime.setText(((user)getUsersList().get(index)).getcrime());
    
  }
   
   
  
     public void setRepQuery() {
    try {
      String sql = "SELECT offId FROM sms_report ";
      this.pst = this.conn.prepareStatement(sql);
      this.rs = this.pst.executeQuery();
      while (this.rs.next()) {
        String joffId = this.rs.getString("offId");
        this.jgender.addItem(joffId);
      } 
    } catch (SQLException r) {
      System.out.println("setQuery Error");
    } 
  }




}
